- name: Default host (specify -l to limit hosts)
  # specify a limit on the command line, using -l or --limit to limit the hosts
  hosts: 'libpcap'

  vars:
    path: "{{ vnf_path | default('/opt/libpcap_echo_server') }}"

  tasks:
  - name: Start service olan-libpcap-echo-server, if not started
    ansible.builtin.service:
      name: olan-libpcap-echo-server
      state: stopped

  - name: Run make uninstall
    community.general.make:
      chdir: "{{ path }}/src"
      target: uninstall

  - name: Delete content & directory
    file:
      state: absent
      path: "{{ path }}/src"