- name: Build the default target
  community.general.make:
    chdir: /opt/libpcap_echo_server

- name: Build the default target
  community.general.make:
    chdir: /opt/libpcap_echo_server
    target: install

# Overide the default conf file
- name: Build the default target
  community.general.make:
    chdir: /opt/libpcap_echo_server
    target: install

- name: Creating a file with content
  copy:
    dest: "/opt/libpcap_echo_server/olan-libpcap-echo-server.conf"
    content: |
      RCV={{ receive_interface }}
      SND={{ send_interface }}
    mode: +x