- name: Default host (specify -l to limit hosts)
  # specify a limit on the command line, using -l or --limit to limit the hosts
  hosts: 'libpcap'

  vars:
    path: "{{ vnf_path | default('/opt/libpcap_echo_server') }}"

  tasks:
  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: "{{ path }}"
      state: directory

  - name: Creating a file with content on {{ path }}
    copy:
      dest: "{{ path }}/src/olan-libpcap-echo-server.conf"
      content: |
        RCV={{ receive_interface }}
        SND={{ send_interface }}
      mode: +x

  - name: Run make in {{ path }}
    community.general.make:
      chdir: "{{ path }}/src"

  - name: Run make install
    community.general.make:
      chdir: "{{ path }}/src"
      target: install