- name: Converge
  hosts: all
  
  vars:
    rcvInterfaceOverride: "{{ lookup('env', 'LIBPCAP_RCV_INTERFACE') }}"
    rcvInterface: "{{ (rcvInterfaceOverride | length > 0) | ternary(rcvInterfaceOverride, 'lo') }}"
    sndInterfaceOverride: "{{ lookup('env', 'LIBPCAP_SND_INTERFACE') }}"
    sndInterface: "{{ (sndInterfaceOverride | length > 0) | ternary(sndInterfaceOverride, 'lo') }}"

  # These tasks are only for testing. During prod the files
  # and tasks are fetched from the git repo and run directly,
  tasks:
    - name: Update apt cache (on Debian).
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: copying file with playbook
      become: true 
      copy:
        src: ../../../src
        dest: /home/libpcap_echo_server
        remote_src: no

- import_playbook: ../../events/instantiate/site.yml

- import_playbook: ../../events/configure/site.yml
  vars:
    vnf_path: /home/libpcap_echo_server

- import_playbook: ../../events/operate/start.yml

- import_playbook: ../../events/operate/stop.yml

- import_playbook: ../../events/terminate/site.yml
  vars:
    vnf_path: /home/libpcap_echo_server