---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
# TODO: change image
- name: instance
  image: ${MOLECULE_DISTRO:-geerlingguy/docker-ubuntu2004-ansible:latest}
  command: ""
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
  pre_build_image: true
  # Add group to read the group variables (makes it configurable)
  groups:
    - libpcap
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: ansible
scenario:
  name: default
  test_sequence: 
    - destroy
    - create
    - converge
    # - idempotence # TODO: enable idempotence
    - lint
    - verify
