- name: Default host (specify -l to limit hosts)
  # specify a limit on the command line, using -l or --limit to limit the hosts
  hosts: 'libpcap'

  tasks:
  - name: Check uptime of remote Ubuntu server
    shell: uptime
    register: command_output

  - debug:
      var: command_output.stdout_lines